import fs from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { Presentation, PresentationFile } from "@oai/artifact-tool";

const SKILL_DIR = "C:/Users/belar/.codex/plugins/cache/openai-primary-runtime/presentations/26.909.12148/skills/presentations";
const TMP_DIR = "C:/Users/belar/AndroidStudioProjects/Quizz/.deck-build";
const OUT = "C:/Users/belar/AndroidStudioProjects/Quizz/pitch-deck/NOVA_AI_Quest_CLOCK_IN_2026_v2.pptx";
const { resolvePresentationFont } = await import(pathToFileURL(path.join(SKILL_DIR, "container_tools/artifact_tool_utils.mjs")).href);
const font = resolvePresentationFont();
const deck = Presentation.create({ slideSize: { width: 1280, height: 720 } });
const C = { bg: "#080C17", surface: "#101629", blue: "#4F8CFF", cyan: "#00D8FF", violet: "#8B5CF6", white: "#F5F7FF", muted: "#A9B5D0", line: "#283454", green: "#57D4A6" };

function box(s, x,y,w,h, fill="none", r=0) { return s.shapes.add({ geometry: r ? "roundRect" : "rect", position:{left:x,top:y,width:w,height:h}, fill, line:{fill:"none",width:0} }); }
function text(s, value, x,y,w,h, size=22, color=C.white, bold=false, align="left") { const q=box(s,x,y,w,h); q.text=value; q.text.style={typeface:font,fontSize:size,color,bold,align,autoFit:"shrinkText"}; return q; }
function title(s, n, heading, sub="") { text(s, `0${n}`,72,44,60,28,15,C.cyan,true); text(s, heading,72,82,1100,55,34,C.white,true); if(sub) text(s,sub,72,140,1050,40,17,C.muted,false); }
function footer(s, n) { text(s,"NOVA AI QUEST  |  CLOCK IN 2026",72,681,350,18,10,C.muted); text(s,String(n),1170,681,38,18,10,C.muted,false,"right"); }
function bullets(s, items, x,y,w, size=20, gap=52) { items.forEach((v,i)=>{ box(s,x,y+i*gap,10,10,C.cyan,5); text(s,v,x+24,y-6+i*gap,w-24,42,size,C.white); }); }
function note(s, t){ s.speakerNotes.textFrame.setText(t); }
function flow(s, labels, y=330) { labels.forEach((v,i)=>{ const x=70+i*194; box(s,x,y,165,80,C.surface,16); text(s,v,x+15,y+20,135,42,18,C.white,true,"center"); if(i<labels.length-1) text(s,"›",x+165,y+19,28,40,32,C.cyan,true,"center"); }); }

// 1
{ const s=deck.slides.add(); s.background.fill=C.bg; box(s,0,0,1280,8,C.cyan); text(s,"NOVA",72,102,360,72,58,C.white,true); text(s,"AI QUEST",72,172,420,56,42,C.cyan,true); text(s,"Turn your learning goal into a quest.",72,251,620,45,28,C.muted); box(s,72,337,630,2,C.line); text(s,"Android app prototype for",72,368,420,28,18,C.white); text(s,"CLOCK IN: Solana Mobile Hackathon 2026",72,402,720,32,22,C.green,true); text(s,"Personalized learning journeys, game-like progress, and a Seeker Daily Quest on Solana Devnet.",72,485,580,70,21,C.white); box(s,826,108,290,290,C.surface,145); text(s,"✦",875,130,190,120,86,C.cyan,true,"center"); text(s,"NOVA",850,276,240,40,27,C.white,true,"center"); text(s,"AI QUEST",850,319,240,28,17,C.muted,true,"center"); footer(s,1); note(s,"Sources: project source code and resources. Hackathon naming and context: https://solanamobile.com/blog/clock-in-the-solana-mobile-hackathon"); }
// 2
{ const s=deck.slides.add(); s.background.fill=C.bg; title(s,2,"The learning-path problem","Product observations, not market statistics"); bullets(s,["A broad learning goal does not automatically become a structured plan.","Learning content can feel fragmented when progress lacks a visible path.","Motivation can fall when feedback and progression arrive too late."],92,245,970,24,90); text(s,"NOVA frames the learning path as a sequence of quests the learner can see and complete.",92,555,1020,35,24,C.cyan,true); footer(s,2); note(s,"Product framing based on implemented journey, chapter, lesson, quiz and progress flows in the project source."); }
// 3
{ const s=deck.slides.add(); s.background.fill=C.bg; title(s,3,"NOVA AI Quest","A goal becomes a structured learning journey"); flow(s,["Goal","AI backend","Journey","Lessons","Quizzes","Progress"],285); text(s,"The Android client sends the goal, level, daily time, and duration to its configured backend. The returned journey contains chapters, lessons, quizzes, and optional challenges.",100,475,1040,70,22,C.white); footer(s,3); note(s,"Sources: MainActivity.kt, GeneratingActivity.kt, GenerateJourneyRequest.kt, ApiService.kt, JourneyResponse.kt, JourneyMapper.kt."); }
// 4
{ const s=deck.slides.add(); s.background.fill=C.bg; title(s,4,"How the product works","Current user flow"); flow(s,["Sign in","Set goal","Generate","Learn","Quiz","Unlock"],230); bullets(s,["Google sign-in creates the user session.","The learner selects level, daily time, and duration before generation.","Passing a lesson quiz marks the lesson complete and updates progress.","Chapter challenges gate chapter completion when present."],92,420,1050,19,52); footer(s,4); note(s,"Sources: WelcomeActivity.kt, AuthManager.kt, MainActivity.kt, GeneratingActivity.kt, LessonActivity.kt, QuizActivity.kt, ResultActivity.kt, ChallengeActivity.kt."); }
// 5
{ const s=deck.slides.add(); s.background.fill=C.bg; title(s,5,"AI-powered personalization","The current backend generates the learning structure"); box(s,90,235,470,250,C.surface,22); text(s,"INPUTS",120,270,180,25,16,C.cyan,true); bullets(s,["Learning goal","Level","Daily time","Duration"],125,318,320,19,42); box(s,700,235,470,250,C.surface,22); text(s,"OUTPUT",730,270,180,25,16,C.cyan,true); bullets(s,["Journey title and description","Chapters and lessons","Quiz questions","Optional chapter challenge"],735,318,345,19,42); text(s,"The source code identifies this component only as an AI-powered backend. It does not identify a model provider or claim autonomous tutoring.",90,550,1060,42,19,C.muted); footer(s,5); note(s,"Sources: RetrofitInstance.kt, ApiService.kt, GenerateJourneyRequest.kt, JourneyResponse.kt. No model/provider is named in the inspected client source."); }
// 6
{ const s=deck.slides.add(); s.background.fill=C.bg; title(s,6,"Game-like progress","Implemented systems make learning state visible"); const a=[["XP & levels","Correct answers add XP. Total XP determines level."],["Coins","Passing quizzes and completing the verified daily quest can add Coins."],["Achievements","Completion milestones are stored in Firestore and can trigger notifications."],["Journey map","Lessons, challenges, and chapter gates control progression."],["Leaderboard","Weekly XP powers a Firestore-backed ranking."],["Cosmetics","Coins unlock and equip Nova visual themes."]]; a.forEach((v,i)=>{let x=72+(i%3)*382,y=220+Math.floor(i/3)*185;box(s,x,y,340,145,C.surface,18);text(s,v[0],x+22,y+20,290,28,21,C.cyan,true);text(s,v[1],x+22,y+58,290,62,16,C.white);}); footer(s,6); note(s,"Sources: ProgressManager.kt, FirebaseProgressManager.kt, AchievementsActivity.kt, LeaderboardActivity.kt, CosmeticsActivity.kt."); }
// 7
{ const s=deck.slides.add(); s.background.fill=C.bg; title(s,7,"Solana verification","Wallet-signed proof for achievements and the Seeker Daily Quest"); flow(s,["Achievement","Wallet sign","Devnet memo","Explorer proof","Daily quest"],250); text(s,"On-Chain Achievement Verification",92,410,520,32,25,C.cyan,true); text(s,"An achievement can be verified on Solana Devnet through a wallet-signed transaction. The transaction includes a Memo identifying the achievement and can be opened in Solana Explorer.",92,452,1015,58,20,C.white); text(s,"For Seeker Daily Quest, a verified wallet can earn +5 in-app Coins once per day after a qualifying quiz.",92,540,1000,30,18,C.white); text(s,"No NFT, token reward, or SKR integration is claimed.",92,589,800,26,17,C.muted); footer(s,7); note(s,"Sources: AchievementsActivity.kt, SolanaAchievementManager.kt, FirebaseProgressManager.kt, SeekerQuestActivity.kt. The achievement flow creates a Devnet memo transaction and exposes the Explorer link."); }
// 8
{ const s=deck.slides.add(); s.background.fill=C.bg; title(s,8,"Product experience","The prototype uses a cohesive dark, game-inspired interface"); const screens=[["Home","Goal input, player stats, Seeker Quest, cosmetics"],["Journey","Chapter map and progress"],["Quiz","Question feedback and explanation"],["Achievements","Milestones and wallet verification action"]]; screens.forEach((v,i)=>{let x=72+i*285;box(s,x,215,238,285,C.surface,22);box(s,x+28,245,182,135,"#141D35",16);text(s,"NOVA",x+55,276,130,26,18,C.cyan,true,"center");text(s,"✦",x+76,312,85,55,36,C.white,true,"center");text(s,v[0],x+23,407,190,28,20,C.white,true,"center");text(s,v[1],x+23,443,190,44,14,C.muted,false,"center");}); text(s,"Illustrative screen representations based on the app’s implemented layouts and branding resources. No runtime screenshots were available in the project files.",72,568,1100,34,16,C.muted); footer(s,8); note(s,"Sources: activity_main.xml, activity_journey.xml, activity_quiz.xml, activity_achievements.xml and drawable resources. This slide intentionally does not represent the mockups as screenshots."); }
// 9
{ const s=deck.slides.add(); s.background.fill=C.bg; title(s,9,"Technology","Verified client-side stack"); const cols=[["Android client","Kotlin\nAndroid SDK\nMaterial Components\nCoroutines"],["Data and network","Firebase Authentication\nCloud Firestore\nCredential Manager\nRetrofit and Gson"],["Media and Solana","Glide\nSolana Mobile Wallet Adapter\nSolana RPC on Devnet"]]; cols.forEach((v,i)=>{let x=82+i*390;box(s,x,240,330,250,C.surface,20);text(s,v[0],x+25,275,275,32,22,C.cyan,true);text(s,v[1],x+25,335,270,112,20,C.white);}); footer(s,9); note(s,"Sources: app/build.gradle.kts, AuthManager.kt, RetrofitInstance.kt, SolanaAchievementManager.kt."); }
// 10
{ const s=deck.slides.add(); s.background.fill=C.bg; title(s,10,"What we built","Verified in the current Android prototype"); box(s,72,210,1080,350,C.surface,20); text(s,"IMPLEMENTED",102,245,250,30,22,C.green,true); bullets(s,["Google authentication and Firestore-backed user data","Generated journeys with lessons, quizzes, and challenges","XP, Coins, levels, achievements, cosmetics, and leaderboard","Wallet-signed Solana Devnet verification for achievements, with Explorer links","Seeker Daily Quest with a once-per-day +5 in-app Coin reward after a qualifying quiz"],110,305,910,18,46); text(s,"Current prototype, verified against the project source.",102,590,760,28,18,C.muted); footer(s,10); note(s,"Sources: project source, including AchievementsActivity.kt, SolanaAchievementManager.kt, FirebaseProgressManager.kt and SeekerQuestActivity.kt."); }
// 11
{ const s=deck.slides.add(); s.background.fill=C.bg; title(s,11,"Future work","Possible directions, not current product claims"); bullets(s,["Richer adaptive learning that responds to learner performance.","Deeper Seeker-native experiences beyond the current verification and daily quest flow.","Broader learning content and additional social or community features.","Additional on-chain utility, subject to product and technical validation."],110,250,960,24,74); text(s,"These items are future directions. They are not presented as implemented capabilities.",110,590,960,32,20,C.cyan,true); footer(s,11); note(s,"Future work proposed in the supplied brief; not represented as present functionality."); }
// 12
{ const s=deck.slides.add(); s.background.fill=C.bg; box(s,0,0,1280,8,C.cyan); text(s,"NOVA AI QUEST",72,156,800,70,52,C.white,true); text(s,"From a learning goal to a playable journey.",72,245,780,45,28,C.cyan); text(s,"A functional Android learning prototype that combines AI-generated journey structure, visible game-like progress, and a precise Solana Devnet Seeker Daily Quest.",72,355,760,76,23,C.white); text(s,"CLOCK IN: Solana Mobile Hackathon 2026",72,520,680,30,19,C.green,true); text(s,"Functional APK  •  GitHub source  •  Demo video  •  Pitch deck",72,566,700,28,17,C.muted); box(s,925,168,180,180,C.surface,90); text(s,"✦",958,205,115,80,62,C.cyan,true,"center"); footer(s,12); note(s,"Product claims: project source. Hackathon submission materials and event facts: https://solanamobile.com/blog/clock-in-the-solana-mobile-hackathon"); }

await fs.mkdir(path.dirname(OUT), {recursive:true});
await (await PresentationFile.exportPptx(deck)).save(OUT);
console.log(OUT);
